### ISSUE TITLE
运行Java文件，无法加载主类错误

### ISSUE THREAD

**Issue by hopeloop** [wwang-dev/MyQqChat#1]
开发者你好！

我把项目clone到本地之后，发现无法运行 ServerFrame.java或Login.java，然后我把src文件夹设置为Sources Root，再运行这两个文件会报错，并显示

> 错误: 找不到或无法加载主类 com.server.view.ServerFrame
> 原因: java.lang.ClassNotFoundException: com.server.view.ServerFrame

如下图：
![image](https://user-images.githubusercontent.com/67470500/94008243-44104600-fdd5-11ea-83bc-c67b6ed4d0b9.png)

请问碰到这种情况应该如何解决呢？

**Comment by 01000011-43** [comment]
<img width="867" alt="image" src="https://user-images.githubusercontent.com/70109581/94020494-8d689180-fde5-11ea-8d79-1439d60ac837.png">
根据lfylfy027 说的，应该是：mysql的文件夹下connector J里面有个.jar文件，是jdbc的驱动，要导入项目的library。
（项目文件右键buildpath，library里add）

**Comment by 01000011-43** [comment]
<img width="867" alt="image" src="https://user-images.githubusercontent.com/70109581/94021069-331c0080-fde6-11ea-822c-a840ac1a6362.png">
我也有遇到这样的问题
根据lfylfy027的说法，应该是mysql的文件夹下connector J里面有个.jar文件，是jdbc的驱动，要导入项目的library。
（项目文件右键buildpath，library里add）
